name: CC-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-front:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build Ionic project
        run: ionic build --prod
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: aspotic-frontend/www
          clean: true
  build-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aspotic-backend
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test