name: CD/CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-aspotic-front:
    runs-on: ubuntu-latest
    container: node:16-alpine
    defaults:
      run:
        working-directory: aspotic-frontend
    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync
        working-directory: ../
      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /__w/sb575.github.io/github-pages-deploy-action-temp-deployment-folder
        working-directory: ../
      - uses: actions/checkout@v2
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://mycnsamastertaii.tech/
          cp www/index.html www/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/master')
        with:
          branch: gh-pages
          folder: aspotic-frontend/www
          clean: true
  build-aspotic-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aspotic-backend
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'un-valor-para-que-no-de-error'
      - name: Adding Known Hosts
        run: ssh-keyscan -H webapps.mycnsamastertaii.tech >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
            ssh ubuntu@webapps.mycnsamastertaii.tech "if [ ! -d 'AspoticMusic' ]; then \
                git clone https://github.com/sb575/AspoticMusic.git; \
              else \
                cd AspoticMusic/aspotic-backend && git stash && git fetch --all && git reset --hard origin/master && git pull origin master; \
              fi"
            ssh ubuntu@webapps.mycnsamastertaii.tech "cd AspoticMusic/aspotic-backend && echo -e 'SPOTIFY_API_ID=${{ secrets.SPOTIFY_API_ID }}\nSPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}' > .env"
            ssh ubuntu@webapps.mycnsamastertaii.tech "cd AspoticMusic/aspotic-backend && docker-compose pull && docker-compose up -d --remove-orphans && yes | docker image prune"